import 'package:flutter/material.dart';
//import 'menu_screen.dart';
//import 'settings_screen.dart'; //TODO: Remove once placeholder screen has been replaced.
import 'package:sight_reading_app/components/app_bar_with_settings_icon.dart';

/// A list containing the keys for each of the buttons generated by build().
List<Key> trackButtonKeys = <Key>[];
/// A list containing the names of each of the play along tracks.
List<String> tracks = <String>[];
///A list containing the user's records for each of the tracks.
List<String> trackRecords = <String>[];

/// A screen containing a menu of the various tracks the user can play along to.
///
/// The tracks are shown as a List of clickable buttons.
/// There is also an AppBar containing the screen title, a back arrow and a setting icon, which when clicked takes you to the settings screen.
class PlayAlongMenuScreen extends StatelessWidget {
  const PlayAlongMenuScreen({Key? key}) : super(key: key);
  ///The key used to identify the screen
  static const String id = 'play_along_menu_screen';

  ///The names of the tracks to user can play along to.
  //May combine with function getRecords() depending on how data is stored and retrieved.
  //TODO: Add ability to get track names from storage
  List<String> getTracks() {
    return <String>['A', 'B', 'C', 'D', 'E', 'F'];
  }

  ///The user records for the tracks you can play along to.
  //May combine with function getTracks() depending on how data is stored and retrieved.
  //TODO: Add ability to get track records from storage
  List<String> getRecords() {
    return <String>['N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A'];
  }

  @override
  Widget build(BuildContext context) {
    tracks = getTracks();
    trackRecords = getRecords();

    trackButtonKeys = <Key>[]; //Resets the list of keys
    ///Generates the keys for the track buttons based on track names.
    for (String track in tracks) {
      trackButtonKeys.add(Key('trackSelected:$track'));
    }

    return const Scaffold(
      appBar: AppBarWithSettingsIcon(Text('Select a track:')),
    );
  }
}