import 'package:flutter/material.dart';
//import 'menu_screen.dart'; //For MenuButton
import 'package:sight_reading_app/components/app_bar_with_settings_icon.dart';

///A list containing the various speedrun mode options.
List<String> modes = <String>[];
///A list containing the keys for each of the buttons generated by build()
List<Key> modeButtonKeys = <Key>[];
///A list containing the user records for each of the modes.
List<String> modeRecords = <String>[];

///A screen that displays a scrollable list of available speedrun modes with buttons to access each mode.
///
/// An app bar is present at the top of the screen, which contains the screen's title text, a back arrow and a clickable settings icon that takes you to the settings screen.
class SpeedrunMenuScreen extends StatelessWidget {
  const SpeedrunMenuScreen({Key? key}) : super(key: key);
  ///The id used to identify the screen.
  static const String id = 'speedrun_menu_screen';

  ///The names of the available speedrun modes.
  //May combine with getRecords() depending on how data is stored.
  //TODO: Add ability to get mode names from storage.
  List<String> getModes() {
    return <String>[
      '10 Seconds',
      '20 seconds',
      '30 seconds',
      '40 seconds',
      '50 seconds',
      '60 seconds'
    ];
  }

  ///The user records for each of the available speedrun modes.
  //May combine with getModes() depending on how data is stored.
  //TODO: Add ability to get records from storage.
  List<String> getRecords() {
    return <String>[
      'N/A',
      'N/A',
      'N/A',
      'N/A',
      'N/A',
      'N/A'
    ];
  }

  @override
  Widget build(BuildContext context) {
    modes = getModes();
    modeRecords = getRecords();
    modeButtonKeys = <Key>[]; //Resets key list
    //Generates the keys for the quiz buttons based on quiz names, with the exception of the random mixed quiz.
    for (String mode in modes) {
      modeButtonKeys.add(Key('modeSelected:$mode'));
    }

    return const Scaffold(
      appBar: AppBarWithSettingsIcon(Text('Choose a duration:')),
    );
  }
}